CREATE TABLE league (
    league_id varchar(255) NOT NULL,
    league_name varchar(50),
    num_rosters integer,
    season integer,
    PRIMARY KEY (league_id)
);

CREATE TABLE roster_user (
    roster_user_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fpts integer,
    fpts_against integer,
    fpts_against_decimal integer,
    fpts_decimal integer,
    league_id varchar(255),
    losses integer,
    roster_id integer,
    ties integer,
    user_id_num varchar(255),
    wins integer,
    PRIMARY KEY (roster_user_id),
    UNIQUE (roster_id, league_id)
);

CREATE TABLE system_metadata (
    key varchar(255) NOT NULL,
    value varchar(255),
    PRIMARY KEY (key)
);

CREATE TABLE users (
    user_id_num varchar(255) NOT NULL,
    display_name varchar(255),
    PRIMARY KEY (user_id_num)
);

CREATE TABLE week_score (
    roster_user_id bigint NOT NULL,
    week_num integer NOT NULL,
    league_id varchar(255),
    score float(53),
    PRIMARY KEY (roster_user_id, week_num)
);

