
    create table app_user (
        email varchar(255) not null,
        name varchar(255),
        primary key (email)
    );

    create table league (
        id varchar(255) not null,
        name varchar(50),
        num_rosters integer,
        season integer,
        primary key (id)
    );

    create table roster_user (
        id bigint generated by default as identity,
        fpts integer,
        fpts_against integer,
        fpts_against_decimal integer,
        fpts_decimal integer,
        losses integer,
        roster_id integer not null,
        ties integer,
        wins integer,
        league_id varchar(255) not null,
        user_id varchar(255) not null,
        primary key (id),
        unique (roster_id, league_id)
    );

    create table system_metadata (
        key varchar(255) not null,
        value varchar(255),
        primary key (key)
    );

    create table users (
        id varchar(255) not null,
        display_name varchar(255),
        primary key (id)
    );

    create table week_score (
        week_num integer not null,
        score float(53),
        roster_user_id bigint not null,
        primary key (roster_user_id, week_num)
    );

    alter table if exists roster_user 
       add constraint fk_league_id 
       foreign key (league_id) 
       references league 
       on delete cascade;

    alter table if exists roster_user 
       add constraint fk_user_id 
       foreign key (user_id) 
       references users 
       on delete cascade;

    alter table if exists week_score 
       add constraint fk_roster_user_id 
       foreign key (roster_user_id) 
       references roster_user 
       on delete cascade;
