
    create table league (
        league_id varchar(255) not null,
        league_name varchar(50),
        num_rosters integer,
        season integer,
        primary key (league_id)
    );

    create table roster_user (
        roster_user_id bigint generated by default as identity,
        fpts integer,
        fpts_against integer,
        fpts_against_decimal integer,
        fpts_decimal integer,
        league_id varchar(255),
        losses integer,
        roster_id integer,
        ties integer,
        user_id_num varchar(255),
        wins integer,
        primary key (roster_user_id),
        unique (roster_id, league_id)
    );

    create table system_metadata (
        key varchar(255) not null,
        value varchar(255),
        primary key (key)
    );

    create table users (
        user_id_num varchar(255) not null,
        display_name varchar(255),
        primary key (user_id_num)
    );

    create table week_score (
        roster_user_id bigint not null,
        week_num integer not null,
        league_id varchar(255),
        score float(53),
        primary key (roster_user_id, week_num)
    );
